### ISSUE TITLE
Issue with trading updates

### ISSUE THREAD

**Issue by fhavellant** [veritacodex/IG.CSharp.Api.Client#1]
I discovered the Topic that the client did not delivery any trade updates that are happening on the account.
For me the issue is that some lines of tradeData at null. 
With the change below i could fix the issue locally.

void SubscriptionListener.onItemUpdate(ItemUpdate itemUpdate)
{
    var json = JsonConvert.SerializeObject(itemUpdate.Fields, Formatting.Indented);
    var tradeData = JsonConvert.DeserializeObject<TradeListenerData>(json);
    if (tradeData.Confirms == null)
    {
        tradeData.Confirms = String.Empty;
    }
    if (tradeData.Opu == null)
    {
        tradeData.Opu = String.Empty;
    }
    if (tradeData.Wou == null)
    {
        tradeData.Wou = String.Empty;
    }
    OnItemUpdateHandler(new TradeListenerEventArgs(tradeData));
}

**Comment by fhavellant** [comment]
the change was done in tradelistener.cs

**Comment by veritacodex** [comment]
Hi, it is not a good idea to hard-code strings, instead of that check if  they are null before processing them at the end. Do not hard-code values.

This is not an issue.
